// Code generated by MockGen. DO NOT EDIT.
// Source: response.go
//
// Generated by this command:
//
//	mockgen -destination mocks/response_gen.go -source response.go
//

// Package mock_http_client is a generated GoMock package.
package mock_http_client

import (
	reflect "reflect"

	http_client "github.com/pixality-inc/golang-core/http_client"
	gomock "go.uber.org/mock/gomock"
)

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
	isgomock struct{}
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// DecodeJSON mocks base method.
func (m *MockResponse) DecodeJSON(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecodeJSON", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecodeJSON indicates an expected call of DecodeJSON.
func (mr *MockResponseMockRecorder) DecodeJSON(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecodeJSON", reflect.TypeOf((*MockResponse)(nil).DecodeJSON), v)
}

// GetBody mocks base method.
func (m *MockResponse) GetBody() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockResponseMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockResponse)(nil).GetBody))
}

// GetHeaders mocks base method.
func (m *MockResponse) GetHeaders() http_client.Headers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaders")
	ret0, _ := ret[0].(http_client.Headers)
	return ret0
}

// GetHeaders indicates an expected call of GetHeaders.
func (mr *MockResponseMockRecorder) GetHeaders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaders", reflect.TypeOf((*MockResponse)(nil).GetHeaders))
}

// GetStatusCode mocks base method.
func (m *MockResponse) GetStatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetStatusCode indicates an expected call of GetStatusCode.
func (mr *MockResponseMockRecorder) GetStatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusCode", reflect.TypeOf((*MockResponse)(nil).GetStatusCode))
}

// String mocks base method.
func (m *MockResponse) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockResponseMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockResponse)(nil).String))
}

// MockTypedResponse is a mock of TypedResponse interface.
type MockTypedResponse[OUT any] struct {
	ctrl     *gomock.Controller
	recorder *MockTypedResponseMockRecorder[OUT]
	isgomock struct{}
}

// MockTypedResponseMockRecorder is the mock recorder for MockTypedResponse.
type MockTypedResponseMockRecorder[OUT any] struct {
	mock *MockTypedResponse[OUT]
}

// NewMockTypedResponse creates a new mock instance.
func NewMockTypedResponse[OUT any](ctrl *gomock.Controller) *MockTypedResponse[OUT] {
	mock := &MockTypedResponse[OUT]{ctrl: ctrl}
	mock.recorder = &MockTypedResponseMockRecorder[OUT]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTypedResponse[OUT]) EXPECT() *MockTypedResponseMockRecorder[OUT] {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockTypedResponse[OUT]) GetBody() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockTypedResponseMockRecorder[OUT]) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockTypedResponse[OUT])(nil).GetBody))
}

// GetEntity mocks base method.
func (m *MockTypedResponse[OUT]) GetEntity() OUT {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntity")
	ret0, _ := ret[0].(OUT)
	return ret0
}

// GetEntity indicates an expected call of GetEntity.
func (mr *MockTypedResponseMockRecorder[OUT]) GetEntity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntity", reflect.TypeOf((*MockTypedResponse[OUT])(nil).GetEntity))
}

// GetHeaders mocks base method.
func (m *MockTypedResponse[OUT]) GetHeaders() http_client.Headers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaders")
	ret0, _ := ret[0].(http_client.Headers)
	return ret0
}

// GetHeaders indicates an expected call of GetHeaders.
func (mr *MockTypedResponseMockRecorder[OUT]) GetHeaders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaders", reflect.TypeOf((*MockTypedResponse[OUT])(nil).GetHeaders))
}

// GetStatusCode mocks base method.
func (m *MockTypedResponse[OUT]) GetStatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetStatusCode indicates an expected call of GetStatusCode.
func (mr *MockTypedResponseMockRecorder[OUT]) GetStatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusCode", reflect.TypeOf((*MockTypedResponse[OUT])(nil).GetStatusCode))
}

// String mocks base method.
func (m *MockTypedResponse[OUT]) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockTypedResponseMockRecorder[OUT]) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockTypedResponse[OUT])(nil).String))
}
