// Code generated by MockGen. DO NOT EDIT.
// Source: stream_response.go
//
// Generated by this command:
//
//	mockgen -destination mocks/stream_response_gen.go -source stream_response.go
//

// Package mock_http_client is a generated GoMock package.
package mock_http_client

import (
	io "io"
	reflect "reflect"

	http_client "github.com/pixality-inc/golang-core/http_client"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamResponse is a mock of StreamResponse interface.
type MockStreamResponse struct {
	ctrl     *gomock.Controller
	recorder *MockStreamResponseMockRecorder
	isgomock struct{}
}

// MockStreamResponseMockRecorder is the mock recorder for MockStreamResponse.
type MockStreamResponseMockRecorder struct {
	mock *MockStreamResponse
}

// NewMockStreamResponse creates a new mock instance.
func NewMockStreamResponse(ctrl *gomock.Controller) *MockStreamResponse {
	mock := &MockStreamResponse{ctrl: ctrl}
	mock.recorder = &MockStreamResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamResponse) EXPECT() *MockStreamResponseMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockStreamResponse) GetBody() io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockStreamResponseMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockStreamResponse)(nil).GetBody))
}

// GetHeaders mocks base method.
func (m *MockStreamResponse) GetHeaders() http_client.Headers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaders")
	ret0, _ := ret[0].(http_client.Headers)
	return ret0
}

// GetHeaders indicates an expected call of GetHeaders.
func (mr *MockStreamResponseMockRecorder) GetHeaders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaders", reflect.TypeOf((*MockStreamResponse)(nil).GetHeaders))
}

// GetStatusCode mocks base method.
func (m *MockStreamResponse) GetStatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetStatusCode indicates an expected call of GetStatusCode.
func (mr *MockStreamResponseMockRecorder) GetStatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusCode", reflect.TypeOf((*MockStreamResponse)(nil).GetStatusCode))
}
