// Code generated by MockGen. DO NOT EDIT.
// Source: local_storage.go
//
// Generated by this command:
//
//	mockgen -destination mocks/local_storage_gen.go -source local_storage.go
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	io "io"
	reflect "reflect"

	storage "github.com/pixality-inc/golang-core/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
	isgomock struct{}
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockLocalStorage) AbortMultipartUpload(ctx context.Context, path, uploadId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, path, uploadId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockLocalStorageMockRecorder) AbortMultipartUpload(ctx, path, uploadId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockLocalStorage)(nil).AbortMultipartUpload), ctx, path, uploadId)
}

// Close mocks base method.
func (m *MockLocalStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLocalStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLocalStorage)(nil).Close))
}

// CompleteMultipartUpload mocks base method.
func (m *MockLocalStorage) CompleteMultipartUpload(ctx context.Context, path, uploadId string, chunks []storage.MultipartChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, path, uploadId, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockLocalStorageMockRecorder) CompleteMultipartUpload(ctx, path, uploadId, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockLocalStorage)(nil).CompleteMultipartUpload), ctx, path, uploadId, chunks)
}

// CreateMultipartUpload mocks base method.
func (m *MockLocalStorage) CreateMultipartUpload(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockLocalStorageMockRecorder) CreateMultipartUpload(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockLocalStorage)(nil).CreateMultipartUpload), ctx, path)
}

// DeleteDir mocks base method.
func (m *MockLocalStorage) DeleteDir(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDir", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDir indicates an expected call of DeleteDir.
func (mr *MockLocalStorageMockRecorder) DeleteDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDir", reflect.TypeOf((*MockLocalStorage)(nil).DeleteDir), ctx, path)
}

// DeleteFile mocks base method.
func (m *MockLocalStorage) DeleteFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockLocalStorageMockRecorder) DeleteFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockLocalStorage)(nil).DeleteFile), ctx, path)
}

// DownloadFile mocks base method.
func (m *MockLocalStorage) DownloadFile(ctx context.Context, path, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, path, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockLocalStorageMockRecorder) DownloadFile(ctx, path, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockLocalStorage)(nil).DownloadFile), ctx, path, filename)
}

// FileExists mocks base method.
func (m *MockLocalStorage) FileExists(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockLocalStorageMockRecorder) FileExists(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockLocalStorage)(nil).FileExists), ctx, path)
}

// GetPublicUrl mocks base method.
func (m *MockLocalStorage) GetPublicUrl(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicUrl", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicUrl indicates an expected call of GetPublicUrl.
func (mr *MockLocalStorageMockRecorder) GetPublicUrl(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicUrl", reflect.TypeOf((*MockLocalStorage)(nil).GetPublicUrl), ctx, path)
}

// LocalPath mocks base method.
func (m *MockLocalStorage) LocalPath(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalPath", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocalPath indicates an expected call of LocalPath.
func (mr *MockLocalStorageMockRecorder) LocalPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalPath", reflect.TypeOf((*MockLocalStorage)(nil).LocalPath), ctx, path)
}

// MkDir mocks base method.
func (m *MockLocalStorage) MkDir(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkDir", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkDir indicates an expected call of MkDir.
func (mr *MockLocalStorageMockRecorder) MkDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkDir", reflect.TypeOf((*MockLocalStorage)(nil).MkDir), ctx, path)
}

// ReadDir mocks base method.
func (m *MockLocalStorage) ReadDir(ctx context.Context, path string) ([]storage.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, path)
	ret0, _ := ret[0].([]storage.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockLocalStorageMockRecorder) ReadDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockLocalStorage)(nil).ReadDir), ctx, path)
}

// ReadFile mocks base method.
func (m *MockLocalStorage) ReadFile(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockLocalStorageMockRecorder) ReadFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockLocalStorage)(nil).ReadFile), ctx, path)
}

// UploadMultipartChunk mocks base method.
func (m *MockLocalStorage) UploadMultipartChunk(ctx context.Context, path, uploadId string, chunkNumber int, body io.Reader, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadMultipartChunk", ctx, path, uploadId, chunkNumber, body, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadMultipartChunk indicates an expected call of UploadMultipartChunk.
func (mr *MockLocalStorageMockRecorder) UploadMultipartChunk(ctx, path, uploadId, chunkNumber, body, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadMultipartChunk", reflect.TypeOf((*MockLocalStorage)(nil).UploadMultipartChunk), ctx, path, uploadId, chunkNumber, body, size)
}

// Write mocks base method.
func (m *MockLocalStorage) Write(ctx context.Context, path string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, path, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockLocalStorageMockRecorder) Write(ctx, path, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLocalStorage)(nil).Write), ctx, path, file)
}

// WriteFile mocks base method.
func (m *MockLocalStorage) WriteFile(ctx context.Context, path, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", ctx, path, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockLocalStorageMockRecorder) WriteFile(ctx, path, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockLocalStorage)(nil).WriteFile), ctx, path, filename)
}

// MockLocalStorageProvider is a mock of LocalStorageProvider interface.
type MockLocalStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageProviderMockRecorder
	isgomock struct{}
}

// MockLocalStorageProviderMockRecorder is the mock recorder for MockLocalStorageProvider.
type MockLocalStorageProviderMockRecorder struct {
	mock *MockLocalStorageProvider
}

// NewMockLocalStorageProvider creates a new mock instance.
func NewMockLocalStorageProvider(ctrl *gomock.Controller) *MockLocalStorageProvider {
	mock := &MockLocalStorageProvider{ctrl: ctrl}
	mock.recorder = &MockLocalStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorageProvider) EXPECT() *MockLocalStorageProviderMockRecorder {
	return m.recorder
}

// AbortMultipartUpload mocks base method.
func (m *MockLocalStorageProvider) AbortMultipartUpload(ctx context.Context, path, uploadId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultipartUpload", ctx, path, uploadId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultipartUpload indicates an expected call of AbortMultipartUpload.
func (mr *MockLocalStorageProviderMockRecorder) AbortMultipartUpload(ctx, path, uploadId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultipartUpload", reflect.TypeOf((*MockLocalStorageProvider)(nil).AbortMultipartUpload), ctx, path, uploadId)
}

// Close mocks base method.
func (m *MockLocalStorageProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLocalStorageProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLocalStorageProvider)(nil).Close))
}

// CompleteMultipartUpload mocks base method.
func (m *MockLocalStorageProvider) CompleteMultipartUpload(ctx context.Context, path, uploadId string, chunks []storage.MultipartChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultipartUpload", ctx, path, uploadId, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteMultipartUpload indicates an expected call of CompleteMultipartUpload.
func (mr *MockLocalStorageProviderMockRecorder) CompleteMultipartUpload(ctx, path, uploadId, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultipartUpload", reflect.TypeOf((*MockLocalStorageProvider)(nil).CompleteMultipartUpload), ctx, path, uploadId, chunks)
}

// CreateMultipartUpload mocks base method.
func (m *MockLocalStorageProvider) CreateMultipartUpload(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultipartUpload", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultipartUpload indicates an expected call of CreateMultipartUpload.
func (mr *MockLocalStorageProviderMockRecorder) CreateMultipartUpload(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultipartUpload", reflect.TypeOf((*MockLocalStorageProvider)(nil).CreateMultipartUpload), ctx, path)
}

// DeleteDir mocks base method.
func (m *MockLocalStorageProvider) DeleteDir(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDir", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDir indicates an expected call of DeleteDir.
func (mr *MockLocalStorageProviderMockRecorder) DeleteDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDir", reflect.TypeOf((*MockLocalStorageProvider)(nil).DeleteDir), ctx, path)
}

// DeleteFile mocks base method.
func (m *MockLocalStorageProvider) DeleteFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockLocalStorageProviderMockRecorder) DeleteFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockLocalStorageProvider)(nil).DeleteFile), ctx, path)
}

// FileExists mocks base method.
func (m *MockLocalStorageProvider) FileExists(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockLocalStorageProviderMockRecorder) FileExists(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockLocalStorageProvider)(nil).FileExists), ctx, path)
}

// LocalPath mocks base method.
func (m *MockLocalStorageProvider) LocalPath(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalPath", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LocalPath indicates an expected call of LocalPath.
func (mr *MockLocalStorageProviderMockRecorder) LocalPath(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalPath", reflect.TypeOf((*MockLocalStorageProvider)(nil).LocalPath), ctx, path)
}

// MkDir mocks base method.
func (m *MockLocalStorageProvider) MkDir(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkDir", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkDir indicates an expected call of MkDir.
func (mr *MockLocalStorageProviderMockRecorder) MkDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkDir", reflect.TypeOf((*MockLocalStorageProvider)(nil).MkDir), ctx, path)
}

// ReadDir mocks base method.
func (m *MockLocalStorageProvider) ReadDir(ctx context.Context, path string) ([]storage.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, path)
	ret0, _ := ret[0].([]storage.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockLocalStorageProviderMockRecorder) ReadDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockLocalStorageProvider)(nil).ReadDir), ctx, path)
}

// ReadFile mocks base method.
func (m *MockLocalStorageProvider) ReadFile(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockLocalStorageProviderMockRecorder) ReadFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockLocalStorageProvider)(nil).ReadFile), ctx, path)
}

// UploadMultipartChunk mocks base method.
func (m *MockLocalStorageProvider) UploadMultipartChunk(ctx context.Context, path, uploadId string, chunkNumber int, body io.Reader, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadMultipartChunk", ctx, path, uploadId, chunkNumber, body, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadMultipartChunk indicates an expected call of UploadMultipartChunk.
func (mr *MockLocalStorageProviderMockRecorder) UploadMultipartChunk(ctx, path, uploadId, chunkNumber, body, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadMultipartChunk", reflect.TypeOf((*MockLocalStorageProvider)(nil).UploadMultipartChunk), ctx, path, uploadId, chunkNumber, body, size)
}

// Write mocks base method.
func (m *MockLocalStorageProvider) Write(ctx context.Context, path string, file io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, path, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockLocalStorageProviderMockRecorder) Write(ctx, path, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLocalStorageProvider)(nil).Write), ctx, path, file)
}
