// Code generated by MockGen. DO NOT EDIT.
// Source: script_driver.go
//
// Generated by this command:
//
//	mockgen -destination mocks/script_driver_gen.go -source script_driver.go
//

// Package mock_flow is a generated GoMock package.
package mock_flow

import (
	context "context"
	reflect "reflect"

	flow "github.com/pixality-inc/golang-core/flow"
	gomock "go.uber.org/mock/gomock"
)

// MockScriptDriver is a mock of ScriptDriver interface.
type MockScriptDriver struct {
	ctrl     *gomock.Controller
	recorder *MockScriptDriverMockRecorder
	isgomock struct{}
}

// MockScriptDriverMockRecorder is the mock recorder for MockScriptDriver.
type MockScriptDriverMockRecorder struct {
	mock *MockScriptDriver
}

// NewMockScriptDriver creates a new mock instance.
func NewMockScriptDriver(ctrl *gomock.Controller) *MockScriptDriver {
	mock := &MockScriptDriver{ctrl: ctrl}
	mock.recorder = &MockScriptDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptDriver) EXPECT() *MockScriptDriverMockRecorder {
	return m.recorder
}

// AnyToValue mocks base method.
func (m *MockScriptDriver) AnyToValue(value any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnyToValue", value)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnyToValue indicates an expected call of AnyToValue.
func (mr *MockScriptDriverMockRecorder) AnyToValue(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnyToValue", reflect.TypeOf((*MockScriptDriver)(nil).AnyToValue), value)
}

// Execute mocks base method.
func (m *MockScriptDriver) Execute(ctx context.Context, env *flow.Env, name, script string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, env, name, script)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockScriptDriverMockRecorder) Execute(ctx, env, name, script any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockScriptDriver)(nil).Execute), ctx, env, name, script)
}

// ValueToBool mocks base method.
func (m *MockScriptDriver) ValueToBool(value any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueToBool", value)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValueToBool indicates an expected call of ValueToBool.
func (mr *MockScriptDriverMockRecorder) ValueToBool(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueToBool", reflect.TypeOf((*MockScriptDriver)(nil).ValueToBool), value)
}

// ValueToMapStringString mocks base method.
func (m *MockScriptDriver) ValueToMapStringString(value any) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueToMapStringString", value)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValueToMapStringString indicates an expected call of ValueToMapStringString.
func (mr *MockScriptDriverMockRecorder) ValueToMapStringString(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueToMapStringString", reflect.TypeOf((*MockScriptDriver)(nil).ValueToMapStringString), value)
}

// ValueToString mocks base method.
func (m *MockScriptDriver) ValueToString(value any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueToString", value)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValueToString indicates an expected call of ValueToString.
func (mr *MockScriptDriverMockRecorder) ValueToString(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueToString", reflect.TypeOf((*MockScriptDriver)(nil).ValueToString), value)
}

// ValueToStringSlice mocks base method.
func (m *MockScriptDriver) ValueToStringSlice(value any) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueToStringSlice", value)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValueToStringSlice indicates an expected call of ValueToStringSlice.
func (mr *MockScriptDriverMockRecorder) ValueToStringSlice(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueToStringSlice", reflect.TypeOf((*MockScriptDriver)(nil).ValueToStringSlice), value)
}
