// Code generated by MockGen. DO NOT EDIT.
// Source: template_driver.go
//
// Generated by this command:
//
//	mockgen -destination mocks/template_driver_gen.go -source template_driver.go
//

// Package mock_flow is a generated GoMock package.
package mock_flow

import (
	context "context"
	reflect "reflect"

	flow "github.com/pixality-inc/golang-core/flow"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateDriver is a mock of TemplateDriver interface.
type MockTemplateDriver struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateDriverMockRecorder
	isgomock struct{}
}

// MockTemplateDriverMockRecorder is the mock recorder for MockTemplateDriver.
type MockTemplateDriverMockRecorder struct {
	mock *MockTemplateDriver
}

// NewMockTemplateDriver creates a new mock instance.
func NewMockTemplateDriver(ctrl *gomock.Controller) *MockTemplateDriver {
	mock := &MockTemplateDriver{ctrl: ctrl}
	mock.recorder = &MockTemplateDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateDriver) EXPECT() *MockTemplateDriverMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTemplateDriver) Execute(ctx context.Context, env *flow.Env, name, source string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, env, name, source)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTemplateDriverMockRecorder) Execute(ctx, env, name, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTemplateDriver)(nil).Execute), ctx, env, name, source)
}
