// Code generated by MockGen. DO NOT EDIT.
// Source: future_test.go
//
// Generated by this command:
//
//	mockgen -destination mocks/activity_future_gen.go -source future_test.go -package mock_temporal
//

// Package mock_temporal is a generated GoMock package.
package mock_temporal

import (
	reflect "reflect"

	workflow "go.temporal.io/sdk/workflow"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityFuture is a mock of ActivityFuture interface.
type MockActivityFuture struct {
	ctrl     *gomock.Controller
	recorder *MockActivityFutureMockRecorder
	isgomock struct{}
}

// MockActivityFutureMockRecorder is the mock recorder for MockActivityFuture.
type MockActivityFutureMockRecorder struct {
	mock *MockActivityFuture
}

// NewMockActivityFuture creates a new mock instance.
func NewMockActivityFuture(ctrl *gomock.Controller) *MockActivityFuture {
	mock := &MockActivityFuture{ctrl: ctrl}
	mock.recorder = &MockActivityFutureMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityFuture) EXPECT() *MockActivityFutureMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockActivityFuture) Get(ctx workflow.Context, outRef any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, outRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockActivityFutureMockRecorder) Get(ctx, outRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockActivityFuture)(nil).Get), ctx, outRef)
}

// IsReady mocks base method.
func (m *MockActivityFuture) IsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockActivityFutureMockRecorder) IsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockActivityFuture)(nil).IsReady))
}
