// Code generated by MockGen. DO NOT EDIT.
// Source: activity.go
//
// Generated by this command:
//
//	mockgen -destination mocks/activity_gen.go -source activity.go
//

// Package mock_temporal is a generated GoMock package.
package mock_temporal

import (
	reflect "reflect"
	time "time"

	temporal "github.com/pixality-inc/golang-core/temporal"
	gomock "go.uber.org/mock/gomock"
)

// MockActivity is a mock of Activity interface.
type MockActivity struct {
	ctrl     *gomock.Controller
	recorder *MockActivityMockRecorder
	isgomock struct{}
}

// MockActivityMockRecorder is the mock recorder for MockActivity.
type MockActivityMockRecorder struct {
	mock *MockActivity
}

// NewMockActivity creates a new mock instance.
func NewMockActivity(ctrl *gomock.Controller) *MockActivity {
	mock := &MockActivity{ctrl: ctrl}
	mock.recorder = &MockActivityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivity) EXPECT() *MockActivityMockRecorder {
	return m.recorder
}

// MaxAttempts mocks base method.
func (m *MockActivity) MaxAttempts() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxAttempts")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxAttempts indicates an expected call of MaxAttempts.
func (mr *MockActivityMockRecorder) MaxAttempts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxAttempts", reflect.TypeOf((*MockActivity)(nil).MaxAttempts))
}

// Name mocks base method.
func (m *MockActivity) Name() temporal.ActivityName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(temporal.ActivityName)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockActivityMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockActivity)(nil).Name))
}

// Queue mocks base method.
func (m *MockActivity) Queue() temporal.QueueName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queue")
	ret0, _ := ret[0].(temporal.QueueName)
	return ret0
}

// Queue indicates an expected call of Queue.
func (mr *MockActivityMockRecorder) Queue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queue", reflect.TypeOf((*MockActivity)(nil).Queue))
}

// RetryBackoffCoefficient mocks base method.
func (m *MockActivity) RetryBackoffCoefficient() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryBackoffCoefficient")
	ret0, _ := ret[0].(float64)
	return ret0
}

// RetryBackoffCoefficient indicates an expected call of RetryBackoffCoefficient.
func (mr *MockActivityMockRecorder) RetryBackoffCoefficient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryBackoffCoefficient", reflect.TypeOf((*MockActivity)(nil).RetryBackoffCoefficient))
}

// RetryInitialInterval mocks base method.
func (m *MockActivity) RetryInitialInterval() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryInitialInterval")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RetryInitialInterval indicates an expected call of RetryInitialInterval.
func (mr *MockActivityMockRecorder) RetryInitialInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryInitialInterval", reflect.TypeOf((*MockActivity)(nil).RetryInitialInterval))
}

// RetryMaximumInterval mocks base method.
func (m *MockActivity) RetryMaximumInterval() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryMaximumInterval")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// RetryMaximumInterval indicates an expected call of RetryMaximumInterval.
func (mr *MockActivityMockRecorder) RetryMaximumInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryMaximumInterval", reflect.TypeOf((*MockActivity)(nil).RetryMaximumInterval))
}

// Timeout mocks base method.
func (m *MockActivity) Timeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timeout indicates an expected call of Timeout.
func (mr *MockActivityMockRecorder) Timeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timeout", reflect.TypeOf((*MockActivity)(nil).Timeout))
}
