// Code generated by MockGen. DO NOT EDIT.
// Source: future.go
//
// Generated by this command:
//
//	mockgen -destination mocks/future_gen.go -source future.go
//

// Package mock_temporal is a generated GoMock package.
package mock_temporal

import (
	reflect "reflect"

	workflow "go.temporal.io/sdk/workflow"
	gomock "go.uber.org/mock/gomock"
)

// MockAwaitable is a mock of Awaitable interface.
type MockAwaitable struct {
	ctrl     *gomock.Controller
	recorder *MockAwaitableMockRecorder
	isgomock struct{}
}

// MockAwaitableMockRecorder is the mock recorder for MockAwaitable.
type MockAwaitableMockRecorder struct {
	mock *MockAwaitable
}

// NewMockAwaitable creates a new mock instance.
func NewMockAwaitable(ctrl *gomock.Controller) *MockAwaitable {
	mock := &MockAwaitable{ctrl: ctrl}
	mock.recorder = &MockAwaitableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAwaitable) EXPECT() *MockAwaitableMockRecorder {
	return m.recorder
}

// Future mocks base method.
func (m *MockAwaitable) Future() workflow.Future {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Future")
	ret0, _ := ret[0].(workflow.Future)
	return ret0
}

// Future indicates an expected call of Future.
func (mr *MockAwaitableMockRecorder) Future() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Future", reflect.TypeOf((*MockAwaitable)(nil).Future))
}

// Name mocks base method.
func (m *MockAwaitable) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockAwaitableMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockAwaitable)(nil).Name))
}
