// Code generated by MockGen. DO NOT EDIT.
// Source: loggable.go
//
// Generated by this command:
//
//	mockgen -destination mocks/logagable_gen.go -source loggable.go
//

// Package mock_logger is a generated GoMock package.
package mock_logger

import (
	context "context"
	reflect "reflect"

	logger "github.com/pixality-inc/golang-core/logger"
	gomock "go.uber.org/mock/gomock"
)

// MockLoggable is a mock of Loggable interface.
type MockLoggable struct {
	ctrl     *gomock.Controller
	recorder *MockLoggableMockRecorder
	isgomock struct{}
}

// MockLoggableMockRecorder is the mock recorder for MockLoggable.
type MockLoggableMockRecorder struct {
	mock *MockLoggable
}

// NewMockLoggable creates a new mock instance.
func NewMockLoggable(ctrl *gomock.Controller) *MockLoggable {
	mock := &MockLoggable{ctrl: ctrl}
	mock.recorder = &MockLoggableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggable) EXPECT() *MockLoggableMockRecorder {
	return m.recorder
}

// GetLogger mocks base method.
func (m *MockLoggable) GetLogger(ctx context.Context) logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogger", ctx)
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// GetLogger indicates an expected call of GetLogger.
func (mr *MockLoggableMockRecorder) GetLogger(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogger", reflect.TypeOf((*MockLoggable)(nil).GetLogger), ctx)
}

// GetLoggerWithoutContext mocks base method.
func (m *MockLoggable) GetLoggerWithoutContext() logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoggerWithoutContext")
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// GetLoggerWithoutContext indicates an expected call of GetLoggerWithoutContext.
func (mr *MockLoggableMockRecorder) GetLoggerWithoutContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoggerWithoutContext", reflect.TypeOf((*MockLoggable)(nil).GetLoggerWithoutContext))
}
